language: python
python:
  - 3.5
  - 3.6

dist:
  trusty

env:
  CODECOV_TOKEN="ac85f735-7a72-4c3c-b032-6e828446833a"

sudo: false

branches:
  only:
    - master
    - dev
    - stagging
  except:
    - stagging

    # Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run test/run_test.py
  - bash sonar_scanner.sh

# Push the results back to codecov
after_success:
  - codecov
