language: python
python:
  - 3.6
  - 3.7
dist: trusty

sudo: false
branches:
  only:
    - master
    - dev
    - stagging
  except:
    - stagging

    # Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run tests.py

# Push the results back to codecov
after_success:
  - codecov
